base_url = "https://ksqsf.moe"
title = "/home/ksqsf"
compile_sass = true
build_search_index = true
generate_feeds = true
author = "ksqsf"

taxonomies = [
  { name="tags", feed=true },
]

[markdown]
highlight_code = true

[slugify]
paths_keep_dates = true

[extra]
favicon = "https://avatars.githubusercontent.com/u/23358293"
