base_url = "https://ksqsf.moe"
title = "/home/ksqsf"
default_language = "zh"
compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml"]
author = "ksqsf"

taxonomies = [
  { name="tags", feed=true },
]

[markdown]
highlight_code = true

[slugify]
paths_keep_dates = true

[extra]
favicon = "https://avatars.githubusercontent.com/u/23358293"

[languages.en]
title = "/home/ksqsf"
generate_feeds = true
feed_filenames = ["rss.xml"]
build_search_index = true
taxonomies = [
  { name="tags", feed=true },
]
